server:
  port: 8082
spring:
  devtools:
      restart:
        enabled: true
  datasource:
        url: jdbc:mysql://localhost:3306/zxspk?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: admin
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
  http:
      encoding:
        force: true
  boot:
    admin:
      client:
        prefer-ip: true
      url: http://localhost:8082

mybatis:
    type-aliases-package: cn.zsk.sys.entity,cn.zsk.snow.manage.entity
    mapper-locations: classpath*:mapper/*.xml
    check-config-location: true

mapper:
    mappers:
        - cn.zsk.core.base.BaseMapper
        - tk.mybatis.mapper.common.Mapper
    not-empty: true
    identity: mysql


# PageHelperConfig 可以替代此方案
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

lenosp:
  uploadPath: ./zFile/file
  isDayType: false

  imagePath: ./zFile/image/

logging:
  file: ./zFile/logs/log.log
  level:
    cn.zsk.*.mapper: debug

dataType: mysql


wechat:
  mp:
    appId: wxecb835c6042d2bd1
    secret: b9e9e8299885ca1192216b43070b14dc
    token: dolphin2018
    aesKey: X7GFhfjC05dGzRCXsZrWMbfkpuK8LJHrtzlCqmH8Sra
